config/routes.rb
Rails.application.routes.draw do

  resources :blogposts

end

app/models/blogpost.rb
class Blogpost
  include Mongoid::Document
  field :title, type: String
  field :camera, type: String
  field :desc, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

	def index
		@blogposts = Blogpost.all
	end

	def show
		@blogpost = Blogpost.find(params[:id])
	end

	def new
		@blogpost = Blogpost.new
	end

	def create
		@blogpost = Blogpost.new(params.require(:blogpost).permit(:title, :camera, :desc))
		if @blogpost.save
			redirect_to blogposts_path
		else
			render 'new'
		end
	end

	def edit
		@blogpost = Blogpost.find(params[:id])
	end

	def update
		@blogpost = Blogpost.find(params[:id])
		if @blogpost.update_attributes(params.require(:blogpost).permit(:title, :camera, :desc))
			redirect_to blogpost_path
		else
			render 'edit'
		end
	end

	def destroy
		@blogpost = Blogpost.find(params[:id])
		@blogpost.destroy
		redirect_to blogposts_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/blogposts/edit.html.erb
    <h1> Edit a Post </h1>

    <%= form_for @blogpost do |f| %>
        Title: <%= f.text_field :title %><br><br>
        Camera: <%= f.text_field :camera %><br><br>
        Description: <%= f.text_field :desc %><br><br>
        

        <%= f.submit "Save Changes" %>

    <% end %><br>

    <%= link_to "Back to the list!", blogposts_path %>

app/views/blogposts/index.html.erb
    <h1>Blog Posts</h1>
    <ul>
        <% @blogposts.each do |b| %>
            <li>
                <strong> <%= b.title %> </strong> -- <%= b.camera %> -- <%= b.desc %> <%= link_to "View Post", blogpost_path(b) %>
            </li>
        <% end %>
    </ul>

        <%= link_to "Create a Post", new_blogpost_path %>

app/views/blogposts/new.html.erb
    <h1> Make a Post </h1>

    <%= form_for @blogpost do |f| %>
        Title: <%= f.text_field :title %><br><br>
        Camera: <%= f.text_field :camera %><br><br>
        Description: <%= f.text_field :desc %><br><br>
        

        <%= f.submit "Add Post!" %>

    <% end %><br>

    <%= link_to "Back to the list!", blogposts_path %>

app/views/blogposts/show.html.erb
    <h1> <%= @blogpost.title %> </h1>

    <p> <%= @blogpost.camera %></p>
    <p> <%= @blogpost.desc %></p>

    <%= link_to "Back to posts", blogposts_path %>
    <%= link_to "Delete this Post", :blogpost, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %>
    <%= link_to "Edit this post", edit_blogpost_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>